### ISSUE TITLE
Automated builds and deploy to bintray

### ISSUE THREAD

**Issue by llinder** [algd/oauth2.0-scala#2]
This project is really nice but it would be handy to pull artifacts from somewhere rather than building from source.  Is there any desire to get this in Bintray or someplace like that?

I'm willing to lend a hand to get that setup if your accepting pull requests for this.

I also see a lot of updates on this fork... https://github.com/Tecsisa/oauth2.0-scala.  Is this where things are maintained now?

**Comment by algd** [comment]
Thanks @llinder !
You are right, but before that, I wanted to improve it so that using this implementation could be easier (I tried it to be flexible but it became a bit complex...), and this probably mean strong changes that I would like to achieve before getting to a more serious maintenance.

About that fork, it contains some updates and changes required in the context where we are using it, and some of them sould end here but not all, thats why I think this refactor is necessary, but now I know that this project could be useful to you I will try to focus on it as soon as possible and, of course, publish it to some repository.

**Comment by briantopping** [comment]
+1 on the great project! :)

Why not deploy to Maven Central and let it propagate from there? Then the artifacts are automatically compatible with both SBT and Maven.

**Comment by llinder** [comment]
@algd thanks!  I appreciate that you want to improve the implementation and look forward to testing it out when ready.

Still it seems like there is value in just getting this out in its current form, even if its not maintained in the long run.  At any rate... please let me know if I can lend a hand.  I will gladly work on getting CI server setup and lend a hand on publishing when your ready :)

@briantopping Maven Central would definitely be nice.  Having published to both Sonatype OSS (gateway for Maven Central) and Bintray, I have to say Bintray is way easier.  I guess if there is a strong desire for Maven Central then it might be worth the extra effort when @algd is ready.

**Comment by algd** [comment]
Sorry for the delay, I wasn't able to spend the time I wanted on it, but it is ready now, so I will try to deploy it to Maven Central soon.

**Comment by MasseGuillaume** [comment]
I'm working on this. I will set you up with Bintray.

**Comment by llinder** [comment]
Nice!  Thanks for taking the time to do this!
