### ISSUE TITLE
Can you provide the database schema? 

### ISSUE THREAD

**Issue by joselufo** [algd/oauth2.0-scala#6]
Would be great to have it.

**Comment by algd** [comment]
Sure, I will finish the documentation this weekend with a suggested schema.

Anyways, although it was firstly built for a key-value database, the library tries not to restrict the way you want to store the data, e.g. you can even not to store tokens and generate/validate them with some encryption/decryption method.

**Comment by algd** [comment]
Ok, I updated the readme.
If you decide to store tokens, 'refresh token' and 'token' tables would be the same as the Authorization code table.
I don't specify how the user is stored because it would not be part of this schema.

You can also check the simple implementation of DataManager used in tests [here](https://github.com/algd/oauth2.0-scala/blob/master/oauth2-scala-core/src/test/scala/io/github/algd/oauth/MyDataManager.scala).
